version: "3"
services:
  python:
    restart: always
    build: .
    container_name: "python3"
    working_dir: "/usr/src/app"
    tty: true
    volumes:
      - ./:/usr/src/app

  code:
    image: codercom/code-server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/coder/project
