version: "3"
services:
  app:
    restart: on-failure:3
    user: root
    build:
      context: .
    tty: true
    environment: 
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILDS=${DISCORD_GUILDS}
      - APP_ENV=${APP_ENV}
    container_name: "natalia"
    working_dir: "/app"
    volumes:
      - ./:/app
  # 
  # code:
  #   image: codercom/code-server
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./:/home/coder/project
